theme: jekyll-theme-cayman
title: Approximate Robust Control of Uncertain Dynamical Systems
description: Edouard Leurent, Yann Blanco, Denis Efimov, Odalric-Ambrym Maillard

github:
  repository_url: http://github.com/eleurent/rl-agents
